### PR TITLE
Rename application binary for consistency

### LINKED ISSUE #57: Make binary name consistent
In general, for any moose project the binary name is the same as the project.

For tmap8, the binary name is tmap. Let's rename this to tmap8 for consistency.

In specific - we need this for apptainer consistency.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #57

### CODE REVIEW

**Comment by loganharbour** [comment]
@simopier please insert frustrations here

images

**Comment by loganharbour** [comment]
@cticenhour should be good now. I'm sure you pinged Alex in that group too, but if not, he approved as well

**Review by cticenhour — APPROVED** [review]
LGTM! Let's see what the tests say.

**Comment by simopier** [comment]
Thank you for taking care of everything here too!

**Review by cticenhour — APPROVED** [review]

**Pull request merged**
