### PR TITLE
Documentation for validation cases 1a-1d

### PR DESCRIPTION
**Pull request by singhgp4321**
#12 

Add documentation for case 1a, 1b, 1c and 1d.

### CODE REVIEW

**Comment by lindsayad** [comment]
@singhgp4321 thank you so much for adding these contributions. Can you make sure that your commit contains an issue reference? E.g. you can run `git commit --amend` and make sure somewhere in the commit message you put "#12"

**Comment by singhgp4321** [comment]
@lindsayad Issue reference added.

**Comment by lindsayad** [comment]
The `val-1c` test result looked it changed a lot ... but you didn't change anything 🤔 I don't know what's going on there. Will have to investigate more. It looks like you deleted the `val-1d.md` file. Was that intentional? With the changes/additions made to the `val-1b.i` input we will have to regold that.

**Comment by singhgp4321** [comment]
val-1d.md was mistakenly deleted, now it's back. Still need to add a couple of comparison plots in that md file; working on it . . .
I'll look into val-1c and will regold 1b.

**Comment by lindsayad** [comment]
if you want some help looking into `val-1c` let me know

**Comment by singhgp4321** [comment]
- val-1b regolded 
- documentation added to the val-1d.md including the comparison plots
- val-1c_out.e was diffing probably because of my mistake; it should pass now

For some reason, the comparison of val-1d results with the analytical solution does not look impressive (val-1d_comparison_diffusion.png). I suspect that some parameter used in the analytical solution (see comparison_val-1d.py)  is not what it should be.

**Comment by lindsayad** [comment]
This is really nice documentation @singhgp4321. I'm super impressed. Probably better than any doc I've ever made 😆 We should try and look into the 1d discrepancies, but that is another task. Thank you!!

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
Sounds good! Just let me know when you want to meetup. I will be out of
town on Monday but should be available on other days

**Pull request merged**
