### PR TITLE
Fixed an issue with the analytical solution for problem val-1d.  

### PR DESCRIPTION
**Pull request by humrickhouse**
The diffusion coefficient in the analytical solution was incorrect; it has been re-set to 1.0 and TMAP8 is now in excellent agreement with the solution.  Also updated the documentation to reflect changes to equation 7 from the original TMAP4 V&V report that were never completely propagated through to values and symbols in the accompanying text.

Refs #12

### CODE REVIEW

**Comment by lindsayad** [comment]
@humrickhouse love the pull request! The failure you're getting on the pre-check is because each pull request needs at least one commit that references an issue. As an example you can look at @singhgp4321's commit https://github.com/idaholab/TMAP8/pull/22/commits/227a3cc749d28d9875737be08fe086b626917c73

You can either create a new issue or reference an existing issue. To edit your commit message, you can run `git commit --amend`

**Comment by cticenhour** [comment]
Thanks Alex! I had already mentioned this to Paul on Slack after he reached out to Gyan and myself. Should have mentioned something here after I made the review request.

**Comment by humrickhouse** [comment]
Ok got the issue reference in there.

**Review by cticenhour — DISMISSED** [review]
Dis-regard this review. Testing permissions.

**Review by singhgp4321 — COMMENTED** [review]
@humrickhouse Your changes look good. Could you also add the updated figure (val-1d_comparison_diffusion.png) for the comparison under doc/content/verification/figures?

**Comment by humrickhouse** [comment]
I can... is there a reason not to use symlinks from the documentation to the testing directory, so the documentation is updated automatically when the tests are run?

**Comment by singhgp4321** [comment]
> I can... is there a reason not to use symlinks from the documentation to the testing directory, so the documentation is updated automatically when the tests are run?

In my knowledge we are not doing the automatic update - currently the documentation plots have to be updated manually. @lindsayad can correct me if that's not the case.

**Comment by lindsayad** [comment]
> so the documentation is updated automatically when the tests are run?

I don't quite know what is meant by this. We do not run any python scripts automatically when the val-1d test suite is run, although we could. If we added python unit tests to the val-1d associated tests, then I think some symlinks would make sense

**Comment by lindsayad** [comment]
@singhgp4321 you want to take a final run-through on this? If it looks good, feel free to approve and merge

**Review by singhgp4321 — APPROVED** [review]

**Pull request merged**
