### PR TITLE
Remove irrelevant notes from documentation

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Reason
I noticed in the documentation of ver-1b the notes section was irrelevant to the problem since it has no traps.
It may be a copy paste from ver-1d.

## Design
Remove the irrelevant notes from ver-1b

## Impact
Improved user experience when reading documentation

### CODE REVIEW

**Comment by cticenhour** [comment]
Good catch @RemDelaporteMathurin - thanks! To get through our CI precheck, could you amend your commit message to include `Refs #79`? We require an issue/ticket reference at least once in the commit history per PR.

**Comment by RemDelaporteMathurin** [comment]
> Good catch @RemDelaporteMathurin - thanks! To get through our CI precheck, could you amend your commit message to include `Refs #79`? We require an issue/ticket reference at least once in the commit history per PR.

I included Refs #79 in the commit message. Sounds a bit restrictive for such small PRs imho 🙄 especially when all that's required is to auto-refer the PR 😄

**Comment by cticenhour** [comment]
> Sounds a bit restrictive for such small PRs imho 🙄 especially when all that's required is to auto-refer the PR 😄

That's a fair opinion 😄 The reason is that we follow the same NQA-1-derived SQA requirement standards as in MOOSE itself, which doesn't account for PR size. 🥲 

Technically, in this case, the full requirement is a filled in template (which I completed for you above) and then a ticket reference. The template is usually done in an Issue, so auto-referring is pretty rare. Our SQA auditors have allowed the auto-refer in the past, so we allow for it here.

**Comment by cticenhour** [comment]
Can you explain what happened with the merge commit here? I don't usually see that happen with a `git commit --amend`.

**Comment by RemDelaporteMathurin** [comment]
> Can you explain what happened with the merge commit here? I don't usually see that happen with a `git commit --amend`.

I don't really know to be honest, I never amend commit messages so I maybe messed something up. 1 commit turned into 2 commits + 1 merge commit 🤷‍♂️

**Comment by cticenhour** [comment]
Very weird. I may be able to squash in the GitHub UI as I merge.

**Review by cticenhour — APPROVED** [review]

**Comment by RemDelaporteMathurin** [comment]
> Very weird. I may be able to squash in the GitHub UI as I merge.

Yes you can choose "Squash and Merge" 
image

**Comment by cticenhour** [comment]
Done - thanks again!

**Pull request merged**
