### PR TITLE
Generate container for fusion blanket model

### PR DESCRIPTION
**Pull request by cticenhour**
DO NOT MERGE. This PR is only being used to generate a TMAP8 container relevant to blanket modeling efforts.

CC: @FranklinTrevor @simopier

### CODE REVIEW

**Comment by cticenhour** [comment]
CIVET is currently down due to HPC datacenter maintenance, so the container will not be generated until it is back online.

**Comment by loganharbour** [comment]
@cticenhour I think you didn't get the registration right here, Trevor is having problems with 

```
*** ERROR ***
A 'FNSFSourceAux' is not a registered object.

If you are trying to find this object in a dynamically loaded library, make sure that
the library can be found either in your "Problem/library_path" parameter or in the
MOOSE_LIBRARY_PATH environment variable.
```

**Comment by cticenhour** [comment]
@loganharbour Probably something to do with my quick and dirty revert to the previous registration. I have about 30 mins before my next meeting - I could try to work it out.

**Comment by cticenhour** [comment]
@loganharbour @FranklinTrevor I reverted back to the old registration function for ModulesApp for now, and a fusion test I picked to check against works as expected (FNSFSourceAux is now found). Let's try this container. Thanks all!

**Comment by cticenhour** [comment]
Paper for new blanket modeling has been submitted - closing this PR.

**Pull request closed without merging**
