### PR TITLE
Adjust documentation and test coverage checks

### PR DESCRIPTION
**Pull request by cticenhour**
- Ignore duplicate bib entries from modules
- Add TMAP7 to V&V description
- Adjust MOOSE language and INL logo on home page

Refs #95
Used to test coverage recipes #93

### CODE REVIEW

**Comment by cticenhour** [comment]
Coverage summary from the `Test` target:
```
Summary coverage rate:
  lines......: 91.0% (315 of 346 lines)
  functions..: 88.5% (46 of 52 functions)
  branches...: no data found
```

**Comment by cticenhour** [comment]
@loganharbour Take a peek and let me know if we need to do anything else here as far as coverage. Some work to do on these test failures after increasing the breadth of our parallel/threads testing, but I will save for later.

**Comment by cticenhour** [comment]
Requesting a review from @loganharbour confirming that the coverage configuration is fully functional (so that we can close #93), and then a review from @simopier on the content adjustments I made.

**Comment by loganharbour** [comment]
Looks good: https://mooseframework.inl.gov/tmap8/docs/PRs/100/coverage/

**Review by loganharbour — APPROVED** [review]
Good on the coverage side. Documentation is up to @simopier.

Diffs will work on PRs once this makes it to devel.

**Comment by cticenhour** [comment]
Thanks for your help here @loganharbour!

**Review by simopier — APPROVED** [review]
Looks great to me, thank you @cticenhour and @loganharbour!

**Pull request merged**
