### PR TITLE
Make verification = '**.md' consistent across verification cases

### PR DESCRIPTION
**Pull request by simopier**
(Ref. #12)

### CODE REVIEW

**Review by cticenhour — APPROVED** [review]

**Comment by cticenhour** [comment]
Wait. The CI-generated VVR doesn't have these listed....I need to explore why. https://mooseframework.inl.gov/tmap8/docs/PRs/165/site/sqa/tmap8_vvr.html

**Comment by simopier** [comment]
@cticenhour - just a gentle ping.

**Comment by cticenhour** [comment]
Thanks for the reminder - I will get to this when I return next week. Maybe Thursday afternoon at the earliest.

**Review by cticenhour — CHANGES_REQUESTED** [review]
Alright, I know what's going on here now. I am working on an issue for MOOSE so that I work on adjusting behavior in MooseDocs. In the meantime, here's what's up:

The `verification` and `validation` parameters need to go down into each test spec, individually, rather than live at the top-level. This is because, as currently designed, one verification document was assumed to pair with one test specification. Given we tend to have multiple tests correspond to a single verification case, this assumption is a poor one for our needs. I will fix it. ~~In the meantime, to close this PR, please restore what was done in `ver-1d` and then emulate that in all other V&V tests. Then I can open a new PR at a later time to make this cleaner once my adjustments are merged into MOOSE.~~

EDIT: We have decided to wait until the fix is in MOOSE to approach this PR again.

**Comment by cticenhour** [comment]
MOOSE PR is idaholab/moose#28916

**Comment by simopier** [comment]
@cticenhour 
Now that https://github.com/idaholab/moose/pull/28916 is merged, can that go in? 

I just restarted the documentation tests.

**Comment by cticenhour** [comment]
This could be merged in, because it doesn't break anything, but won't take full effect until what is in moose next makes it to moose master. Next is blocked last I checked. ☹️

**Comment by cticenhour** [comment]
@simopier I think you need to rebase on top of current devel to get this to work properly. An invalidation doesn't seem to be enough.

**Review by cticenhour — APPROVED** [review]
After the MOOSE fix, the VVR in the doco preview now shows all verification cases selected in this PR. Looks good!

**Pull request merged**
