### PR TITLE
Rename Verification cases to use 'verification' rather than 'validation'

### PR DESCRIPTION
**Pull request by simopier**
The current documentation and file names list verification cases as validation cases. This PR changes that for relevant cases.

This PR therefore does not add any new feature/V&V cases, only renames existing cases and updates the documentation.
(Ref. #12)

### CODE REVIEW

**Review by cticenhour — CHANGES_REQUESTED** [review]
Please remove the merge commits from the main branch by rebasing on `devel` 😄

**Comment by simopier** [comment]
@singhgp4321 this is the PR we had talked about to call verification cases what they are rather than validation cases.

**Review by cticenhour — APPROVED** [review]

**Comment by cticenhour** [comment]
@simopier I approve this, but since you requested review from @singhgp4321 I will leave it to him to merge in case he has any comments.

**Review by singhgp4321 — APPROVED** [review]

**Comment by singhgp4321** [comment]
Looks good to me.

**Pull request merged**
