### PR TITLE
Adding val-2b case

### PR DESCRIPTION
**Pull request by singhgp4321**
Ref: #12

### CODE REVIEW

**Comment by singhgp4321** [comment]
@lindsayad @humrickhouse

**Comment by singhgp4321** [comment]
@lindsayad When you get a chance please add a paragraph on the convergence in the .md file. Do you recommend putting the validation cases under test/tests or in a separate directory which may be called "assessment".

**Comment by lindsayad** [comment]
I would say `test/tests` is good

**Comment by lindsayad** [comment]
It seems like there must be a solve failure, either in the run used to create the gold file, or on CIVET since the times are not the same length

**Comment by singhgp4321** [comment]
There is no solve fail locally so it should be failing only on civet. I will try to create the civet environment on rod with help from @loganharbour and try to track it down.

**Review by lindsayad — APPROVED** [review]

**Comment by simopier** [comment]
Is there any documentation for `SolubilityRatioMaterial` that was added as part of this PR? I don't find any.

**Comment by cticenhour** [comment]
I was about to say that this should have failed CI if it wasn't there, but looks like we have `WARNING` turned on in the SQA config for missing markdown currently. 🤦🏻‍♂️

**Comment by simopier** [comment]
> I was about to say that this should have failed CI if it wasn't there, but looks like we have `WARNING` turned on in the SQA config for missing markdown currently. 🤦🏻‍♂️

Can you update that setting? (I have no idea how to do it)

**Comment by cticenhour** [comment]
I will update it once everything is green (so as not to disrupt submodule updates). Beyond the documentation you mention, `ReleasingNodalKernel`, `TrappingNodalKernel`, `EnclosureSinkNodalKernel`, and `EquilibriumBC` are all missing class descriptions in the C++ source. This should also be fixed (ideally at the same time the documentation is added).

**Comment by cticenhour** [comment]
The issues noted above are being fixed up in #63.

**Pull request merged**
